### ISSUE TITLE
建议：语序调整

### ISSUE THREAD

**Issue by rainssong** [xiaolai/the-self-cultivation-of-leeks#4]
> 然而，我的整个 45 岁，也就是过去的一整年里，我遇到了批量的所谓“坏人”，背叛、欺骗、诬陷、颠倒是非、甚至陷害…… 除了郑伊廷 (@xdite)之外（因为要用她举例），在这里我就不点名了罢

这里可能被误解为：“我遇到了很多‘坏人’，除了郑伊廷（她不是）”，建议修改为：

> 然而，我的整个 45 岁，也就是过去的一整年里，我遇到了批量的所谓“坏人”，背叛、欺骗、诬陷、颠倒是非、甚至陷害…… 在这里我就不点名了罢【除了郑伊廷 (@xdite)，因为要用她举例】

**Comment by xiaolai** [comment]
修改了。
